packages:
  - 'apps/raycast-extension'
  - 'apps/worker-agent'
  - 'packages/*'
allowBuilds:
  esbuild: set this to true or false
  sharp: set this to true or false
  workerd: set this to true or false
