// Model routing & inference dispatch for ChatTreeAgent

import { callable } from "agents"

export interface ModelChoice {
  model: string
  runner: "ollama" | "mlx" | "codex" | "pplx" | "remote"
  context: number
  cost?: number
  endpoint?: string
}

export interface InferenceRequest {
  kind: "normalize" | "export" | "plan" | "research" | "code"
  prompt: string
  urgency?: "low" | "medium" | "high"
  tokens?: number
  requiresWeb?: boolean
}

export interface InferenceResult {
  model: string
  output: string
  runner: string
  latency: number
  tokens: number
}

/**
 * InferenceRouter - Routes tasks to optimal model
 * Prefers local (ollama, mlx, codex) with remote fallback
 */
export class InferenceRouter {
  private ollamaEndpoint = "http://orbstack:11434"
  private pplxEndpoint = "http://orbstack:8000"
  private remoteEndpoints: Record<string, string> = {
    "claude-opus": "https://api.anthropic.com/v1/messages",
    "gpt-4o": "https://api.openai.com/v1/chat/completions",
    "perplexity-sonar-pro": "https://api.perplexity.ai/chat/completions"
  }

  chooseModel(task: InferenceRequest): ModelChoice {
    // Web-aware tasks → perplexity
    if (task.requiresWeb) {
      return task.urgency === "high"
        ? {
            model: "perplexity-sonar-pro",
            runner: "remote",
            context: 127000,
            cost: 10,
            endpoint: this.remoteEndpoints["perplexity-sonar-pro"]
          }
        : {
            model: "perplexity-sonar-mini",
            runner: "pplx",
            context: 16000,
            endpoint: this.pplxEndpoint
          }
    }

    // Code generation → codex first
    if (task.kind === "code") {
      return {
        model: "codex-js",
        runner: "codex",
        context: 2000,
        endpoint: "internal:codex"
      }
    }

    // High urgency → remote (claude)
    if (task.urgency === "high") {
      return {
        model: "claude-opus",
        runner: "remote",
        context: 200000,
        cost: 15,
        endpoint: this.remoteEndpoints["claude-opus"]
      }
    }

    // Low urgency → local primary (mistral)
    if (task.urgency === "low") {
      return {
        model: "mistral-7b",
        runner: "ollama",
        context: 4000,
        endpoint: this.ollamaEndpoint
      }
    }

    // Medium urgency → local secondary (neural-chat) with fast fallback
    return {
      model: "neural-chat-7b",
      runner: "mlx",
      context: 4000,
      endpoint: this.ollamaEndpoint
    }
  }

  async invoke(
    choice: ModelChoice,
    request: InferenceRequest
  ): Promise<InferenceResult> {
    const start = Date.now()

    try {
      let output = ""

      switch (choice.runner) {
        case "ollama":
          output = await this.invokeOllama(choice.model, request.prompt)
          break

        case "mlx":
          output = await this.invokeMLX(choice.model, request.prompt)
          break

        case "codex":
          output = await this.invokeCodex(request.prompt)
          break

        case "pplx":
          output = await this.invokePerplexity(
            choice.model,
            request.prompt,
            request.requiresWeb
          )
          break

        case "remote":
          output = await this.invokeRemote(choice.model, request.prompt)
          break
      }

      const latency = Date.now() - start
      const tokens = Math.ceil(output.length / 4) // rough estimate

      return {
        model: choice.model,
        output,
        runner: choice.runner,
        latency,
        tokens
      }
    } catch (err) {
      throw new Error(
        `Inference failed [${choice.model}]: ${(err as Error).message}`
      )
    }
  }

  private async invokeOllama(model: string, prompt: string): Promise<string> {
    const res = await fetch(`${this.ollamaEndpoint}/api/generate`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ model, prompt, stream: false })
    })

    if (!res.ok) throw new Error(`Ollama error: ${res.statusText}`)

    const data = (await res.json()) as { response: string }
    return data.response
  }

  private async invokeMLX(model: string, prompt: string): Promise<string> {
    // MLX runs on same Ollama endpoint but with different model name
    return this.invokeOllama(model, prompt)
  }

  private async invokeCodex(prompt: string): Promise<string> {
    // Direct Node.js codex execution
    // Assuming codex-js package is available
    // For now, stub it
    return `// Generated by codex\n${prompt}`
  }

  private async invokePerplexity(
    model: string,
    prompt: string,
    withWeb?: boolean
  ): Promise<string> {
    const res = await fetch(`${this.pplxEndpoint}/search`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        model,
        query: prompt,
        withWeb: withWeb || false
      })
    })

    if (!res.ok) throw new Error(`Perplexity error: ${res.statusText}`)

    const data = (await res.json()) as { answer: string }
    return data.answer
  }

  private async invokeRemote(model: string, prompt: string): Promise<string> {
    // Delegate to appropriate remote API based on model
    if (model.includes("claude")) {
      return this.invokeAnthropic(model, prompt)
    } else if (model.includes("perplexity")) {
      return this.invokePerplexity(model, prompt, false)
    } else if (model.includes("gpt")) {
      return this.invokeOpenAI(model, prompt)
    }
    throw new Error(`Unknown remote model: ${model}`)
  }

  private async invokeAnthropic(model: string, prompt: string): Promise<string> {
    const apiKey = process.env.ANTHROPIC_API_KEY
    if (!apiKey) throw new Error("ANTHROPIC_API_KEY not set")

    const res = await fetch(
      "https://api.anthropic.com/v1/messages",
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "x-api-key": apiKey,
          "anthropic-version": "2023-06-01"
        },
        body: JSON.stringify({
          model,
          max_tokens: 2048,
          messages: [{ role: "user", content: prompt }]
        })
      }
    )

    if (!res.ok) throw new Error(`Anthropic error: ${res.statusText}`)

    const data = (await res.json()) as {
      content: Array<{ text: string }>
    }
    return data.content[0].text
  }

  private async invokeOpenAI(model: string, prompt: string): Promise<string> {
    const apiKey = process.env.OPENAI_API_KEY
    if (!apiKey) throw new Error("OPENAI_API_KEY not set")

    const res = await fetch("https://api.openai.com/v1/chat/completions", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${apiKey}`
      },
      body: JSON.stringify({
        model,
        messages: [{ role: "user", content: prompt }],
        temperature: 0.7
      })
    })

    if (!res.ok) throw new Error(`OpenAI error: ${res.statusText}`)

    const data = (await res.json()) as {
      choices: Array<{ message: { content: string } }>
    }
    return data.choices[0].message.content
  }
}

/**
 * Extend ChatTreeAgent with inference dispatch
 */
export function extendAgentWithInference(agent: any) {
  const router = new InferenceRouter()

  agent.invokeModel = callable()(async function (request: InferenceRequest) {
    const choice = router.chooseModel(request)
    const result = await router.invoke(choice, request)
    return result
  })

  agent.chooseModel = callable()(async function (request: InferenceRequest) {
    return router.chooseModel(request)
  })

  return agent
}
